import '@/app/css/style.css'
import { Inter, Playfair_Display } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair-display',
  display: 'swap'
})

export const metadata = {
  title: 'VibeLingo',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ lang: string }>
}) {
  const resolvedParams = await params

  return (
    <html lang={resolvedParams.lang}>
      <body className={`${inter.variable} ${playfair.variable} font-inter antialiased bg-slate-900 text-slate-100 tracking-tight`}>
        {children}
      </body>
    </html>
  )
}